

services:
  # Databastjänsten

  # Grafiskt gränssnitt för databasen (Valfritt men rekommenderat)
    #db:
  #  image: postgres:15-alpine
  #  container_name: farm_postgres
   # restart: always
  #  environment:
   #   POSTGRES_USER: elias      # Användarnamn
   #   POSTGRES_PASSWORD: 6969 # Lösenord
   #   POSTGRES_DB: farm_db           # Databasnamn
   # ports:
   #   - "5432:5432" # Gör databasen tillgänglig på din dator (localhost)
   # volumes:
    #  - db_data:/var/lib/postgresql/data # Sparar datan även om du startar om containern
  db:
    image: postgres:15-alpine
    container_name: farm_postgres
    environment:
      POSTGRES_USER: elias
      POSTGRES_PASSWORD: "6969"
      POSTGRES_DB: farmdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: farm_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    container_name: farm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" # Du når denna på http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  frontend:
    build: /frontend # This points to the folder where your React code is
    container_name: farm_frontend
    ports:
      - "5173:5173"
    stdin_open: true # Keeps the React process from crashing in Docker
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensures "Hot Reload" works on Windows
    volumes:
      - ./Frontend:/app
      - /app/node_modules # Prevents Docker from overwriting your local node_modules

volumes:
  db_data:
  pgadmin_data:


  
